# Generated by Django 4.0.5 on 2022-06-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_usercode_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='email_code',
            field=models.IntegerField(default=None),
        ),
    ]
