# Generated by Django 4.0.5 on 2022-06-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_usercode_email_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercode',
            old_name='email_code',
            new_name='code2',
        ),
    ]
