# Generated by Django 4.0.5 on 2022-06-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_rename_email_code_usercode_code2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercode',
            name='code2',
            field=models.IntegerField(),
        ),
    ]
