# Generated by Django 4.0.5 on 2022-06-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_alter_usercode_code2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercode',
            name='code2',
            field=models.IntegerField(default=0),
        ),
    ]
