# Generated by Django 4.0.5 on 2022-06-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_text_response_resp_text_response_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_advertisement', to='main.advertisement'),
        ),
        migrations.AlterField(
            model_name='response',
            name='resp_text',
            field=models.CharField(max_length=255, verbose_name='Текст'),
        ),
    ]
