# Generated by Django 4.0.5 on 2022-06-15 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_response_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('post', 'user')},
        ),
    ]
