# Generated by Django 4.0.5 on 2022-06-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_response_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='video_link',
            field=models.TextField(null=True),
        ),
    ]
