# Generated by Django 4.0.5 on 2022-06-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_advertisement_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='video_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
